name: BUG MORE AI 编译工作流（支持1.24+）
on:
  push:
    branches: [ "master" ]
    paths:
      - 'MAKEAMAIONLINE.BAT'
      - 'Blizzard.eai'
      - 'common.eai'
      - 'races.eai'
      - 'custom_common.eai'
      - '.github/workflows/bmaibuild.yml'
jobs:
  amai:
    runs-on: windows-2022
    steps:
    - name: 提交源码
      uses: actions/checkout@v4
    - name: 安装环境
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: ${{ matrix.perl-version }}
        distribution: strawberry
        working-directory: ./
    - name: 启动编译工具
      run: perl -V
    - name: 编译脚本
      run: ./MAKEAMAIONLINE.BAT
    - name: 打包战网版脚本
      uses: TheDoctor0/zip-release@0.7.6
      with:
        filename: bug_more_ai_战网版免编译脚本.zip
        path: D:/a/BUG-MORE-AI/BUG-MORE-AI/Scripts/REFORGED
        directory: D:/a/BUG-MORE-AI/BUG-MORE-AI/ZIP/REFORGED
    - name: 打包经典版脚本
      uses: TheDoctor0/zip-release@0.7.6
      with:
        filename: bug_more_ai_经典版免编译脚本.zip
        path: D:/a/BUG-MORE-AI/BUG-MORE-AI/Scripts/TFT
        directory: D:/a/BUG-MORE-AI/BUG-MORE-AI/ZIP/TFT
    - name: 上传战网版脚本压缩包
      uses: actions/upload-artifact@v4
      with:
        name: bug_more_ai_REFORGED_Scripts
        path: ./ZIP/REFORGED
    - name: 上传经典版脚本压缩包
      uses: actions/upload-artifact@v4
      with:
        name: bug_more_ai_TFT_Scripts
        path: ./ZIP/TFT
